### ISSUE TITLE
图挂了一半

### ISSUE THREAD

**Issue by zhongfox** [dzdx/notes#1]
<https://github.com/dzdx/notes/blob/master/envoy/%E8%A7%A3%E6%9E%90envoy%E5%A4%84%E7%90%86http%E8%AF%B7%E6%B1%82%EF%BC%88%E4%B8%80%EF%BC%89%7C%20filter%E6%9E%B6%E6%9E%84.md>
这里面有张图挂了：
![](https://camo.githubusercontent.com/61c7fe3d9e8bad3f4bd06a2a7dadb28a90e217c8/68747470733a2f2f706963676f2d313235393238303434322e636f732e61702d7368616e676861692e6d7971636c6f75642e636f6d2f32303139303630333232303631352e706e67)
能重新上传一下吗？

**Comment by dzdx** [comment]
@zhongfox   更新了

**Comment by zhongfox** [comment]
nice, thx
